### ISSUE TITLE
bug when run pip install keyboxchecker

### ISSUE THREAD

**Issue by ammlrr** [real-LiHua/KeyboxChecker#11]
`Processing ./keyboxchecker-1.1.3-py3-none-any.whl
Collecting cryptography<44.0.0,>=43.0.1 (from keyboxchecker==1.1.3)
  Downloading cryptography-43.0.3.tar.gz (686 kB)
     ━━━━━━━━━━━━━━ 687.0/687.0   404.6 kB/s eta 0:00:00
                    kB
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Collecting maturin<2,>=1
        Downloading maturin-1.7.4.tar.gz (191 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting cffi>=1.12
        Downloading cffi-1.17.1.tar.gz (516 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools!=74.0.0,!=74.1.0,!=74.1.1,!=74.1.2,!=74.1.3,!=75.0.0,!=75.1.0,!=75.2.0
        Downloading setuptools-73.0.1-py3-none-any.whl.metadata (6.6 kB)
      Collecting pycparser (from cffi>=1.12)
        Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
      Downloading setuptools-73.0.1-py3-none-any.whl (2.3 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 217.1 kB/s eta 0:00:00
      Downloading pycparser-2.22-py3-none-any.whl (117 kB)
      Building wheels for collected packages: maturin, cffi
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [43 lines of output]
            /data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py:251: _IncompatibleBdistWheel: wheel.bdist_wheel is deprecated, please import it from setuptools
            !!

                    ********************************************************************************
                    Ensure that any custom bdist_wheel implementation is a subclass of
                    setuptools.command.bdist_wheel.bdist_wheel.

                    By 2025-Oct-15, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.

                    See https://github.com/pypa/wheel/pull/631 for details.
                    ********************************************************************************

            !!
              return _build_backend().build_wheel(wheel_directory, config_settings,
            running bdist_wheel
            running build
            running build_py
            creating build/lib.linux-aarch64-cpython-312/maturin
            copying maturin/__init__.py -> build/lib.linux-aarch64-cpython-312/maturin
            copying maturin/__main__.py -> build/lib.linux-aarch64-cpython-312/maturin
            running egg_info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no files found matching '*.json' under directory 'src/python_interpreter'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
            error: can't find Rust compiler

            If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

            To update pip, run:

                pip install --upgrade pip

            and then retry package installation.

            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'done'
        Created wheel for cffi: filename=cffi-1.17.1-cp312-cp312-linux_aarch64.whl size=336479 sha256=2999843e77f0e4569d4be3b198e8ceb9aaa1d8907268dd59d3ca1e4f893eb771
        Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/2e/18/23/10f816dc1f57d13a6c8d6525d442e74d82e772bb60f864afbe
      Successfully built cffi
      Failed to build maturin
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by real-LiHua** [comment]
Try this.
```bash
pkg install -y rust binutils
CARGO_BUILD_TARGET="$(rustc -Vv | grep "host" | awk '{print $2}')" pip install keyboxchecker
```
